name: ci
on: push
jobs:
  work-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make setup
      - run: make start
      - run: make test
      - run: make lint
